site_name: OpenBOS

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: lucide/moon
        name: Switch to light mode

nav:
  - Home: index.md
  - Quickstarts: quickstarts/quickstarts.md
  - Architecture: overview/architecture.md
  - Interfaces: overview/interfaces.md
  - Web App: web-app/intro.md
  - Python Library: client-libraries/python.md